cloud:
  aws:
    credentials:
      accessKey: AKIAV5APOORJD3PDPPFS
      secretKey: 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
    s3:
      bucket: guam
    region:
      static: ap-northeast-2
    stack:
      auto: false

