spring.config.import:
  - classpath:application-aws.yml

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/guam_test?serverTimezone=UTC&characterEncoding=UTF-8"
    username: root
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
