spring.config.import:
  - classpath:application-aws.yml

spring:
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

