spring.config.import:
  - classpath:application-aws.yml
  - classpath:application-db.yml

spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
