--insert into tech_stacks (id, name, aliases, position)
--values (1, '1', 'dasjlfds', 'FRONTEND'),
--(31, '31', 'dasjlfds', 'BACKEND'),
--(37, '37', 'dasjlfds', 'DESIGNER'),
--(2, '2', 'dasjlfds', 'FRONTEND'),
--(30, '30', 'dasjlfds', 'BACKEND'),
--(3, '3', 'dasjlfds', 'FRONTEND'),
--(32, '32', 'dasjlfds', 'BACKEND'),
--(36, '36', 'dasjlfds', 'DESIGNER');