spring:
  config:
    activate:
      on-profile: prod
  datasource:
      url: ${DB_URL}?serverTimezone=UTC&characterEncoding=UTF-8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
        connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
  jpa:
    properties:
      hibernate:
        show_sql: false
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
  jpa:
    properties:
      hibernate:
        show_sql: false
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password: